name: Bug
description: Something is broken
labels: ["type:bug"]
body:
  - type: textarea
    id: expected
    attributes:
      label: Expected vs actual
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
  - type: input
    id: env
    attributes:
      label: Environment
